install.packages("psych", repos="http://cran.us.r-project.org")
install.packages("rstatix", repos="http://cran.us.r-project.org")
library(psych)
library(rstatix)

# Put the path to the grouped decisions for the clusters. We used Excel for this.
# Put each cluster's R, homogeneity, and correctness as columns and the participants as rows.
# We coded correct decisions as 1 and incorrect as 0. For homogeneity, we calculate the SD for each cluster and participant.
# We named R columns as R_ followed by the cluster name, homogeneity columns starting with H_, and correctness columns starting with C_.

study <- read.csv("PATH", header = TRUE, sep = ";")

kruskal.test(study$R_P1~study$Group)
kruskal.test(study$R_P2~study$Group)
kruskal.test(study$R_P3~study$Group)
kruskal.test(study$R_P4~study$Group)
kruskal.test(study$R_P5~study$Group)
kruskal.test(study$R_N1~study$Group)
kruskal.test(study$R_N2~study$Group)
kruskal.test(study$R_N3~study$Group)
kruskal.test(study$R_N4~study$Group)
kruskal.test(study$R_M1~study$Group)
kruskal.test(study$R_M2~study$Group)

kruskal.test(study$H_P1~study$Group)
kruskal.test(study$H_P2~study$Group)
kruskal.test(study$H_P3~study$Group)
kruskal.test(study$H_P4~study$Group)
kruskal.test(study$H_P5~study$Group)
kruskal.test(study$H_N1~study$Group)
kruskal.test(study$H_N2~study$Group)
kruskal.test(study$H_N3~study$Group)
kruskal.test(study$H_N4~study$Group)
kruskal.test(study$H_M1~study$Group)
kruskal.test(study$H_M2~study$Group)

kruskal.test(study$C_P1~study$Group)
kruskal.test(study$C_P2~study$Group)
kruskal.test(study$C_P3~study$Group)
kruskal.test(study$C_P4~study$Group)
kruskal.test(study$C_P5~study$Group)
kruskal.test(study$C_N1~study$Group)
kruskal.test(study$C_N2~study$Group)
kruskal.test(study$C_N3~study$Group)
kruskal.test(study$C_N4~study$Group)
kruskal.test(study$C_M1~study$Group)
kruskal.test(study$C_M2~study$Group)


dunn_test(ARP~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(t~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(BA~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(MD~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(TD~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(PF~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(FL~Group, data=study, p.adjust.method = "bonferroni")

dunn_test(R_P1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_P2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_P3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_P4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_P5~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_N1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_N2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_N3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_N4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_M1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(R_M2~Group, data=study, p.adjust.method = "bonferroni")

dunn_test(H_P1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_P2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_P3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_P4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_P5~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_N1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_N2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_N3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_N4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_M1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(H_M2~Group, data=study, p.adjust.method = "bonferroni")

dunn_test(C_P1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_P2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_P3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_P4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_P5~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_N1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_N2~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_N3~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_N4~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_M1~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(C_M2~Group, data=study, p.adjust.method = "bonferroni")

