install.packages("psych", repos="http://cran.us.r-project.org")
install.packages("rstatix", repos="http://cran.us.r-project.org")
library(psych)
library(rstatix)

# Put the path to the grouped decisions for the permissions. We used Excel for this.
# Put each permission's correctness as columns and the participants as rows.
# We coded correct decisions as 1 and incorrect as 0.

study <- read.csv("PATH", header = TRUE, sep = ";")

kruskal.test(study$P_1000~study$Group)
kruskal.test(study$P_1001~study$Group)
kruskal.test(study$P_1002~study$Group)
kruskal.test(study$P_1003~study$Group)
kruskal.test(study$P_1004~study$Group)
kruskal.test(study$P_1005~study$Group)
kruskal.test(study$P_1006~study$Group)
kruskal.test(study$P_1007~study$Group)
kruskal.test(study$P_1008~study$Group)
kruskal.test(study$P_1009~study$Group)
kruskal.test(study$P_1010~study$Group)
kruskal.test(study$P_1011~study$Group)
kruskal.test(study$P_1012~study$Group)
kruskal.test(study$P_1013~study$Group)
kruskal.test(study$P_1014~study$Group)
kruskal.test(study$P_1015~study$Group)
kruskal.test(study$P_1016~study$Group)
kruskal.test(study$P_1017~study$Group)
kruskal.test(study$P_1018~study$Group)
kruskal.test(study$P_1019~study$Group)
kruskal.test(study$P_1020~study$Group)
kruskal.test(study$P_1021~study$Group)
kruskal.test(study$P_1022~study$Group)
kruskal.test(study$P_1023~study$Group)
kruskal.test(study$P_1024~study$Group)
kruskal.test(study$P_1025~study$Group)
kruskal.test(study$P_1026~study$Group)
kruskal.test(study$P_1027~study$Group)
kruskal.test(study$P_1028~study$Group)
kruskal.test(study$P_1029~study$Group)


dunn_test(P_1000~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1001~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1002~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1003~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1004~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1005~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1006~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1007~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1008~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1009~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1010~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1011~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1012~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1013~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1014~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1015~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1016~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1017~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1018~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1019~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1020~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1021~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1022~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1023~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1024~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1025~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1026~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1027~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1028~Group, data=study, p.adjust.method = "bonferroni")
dunn_test(P_1029~Group, data=study, p.adjust.method = "bonferroni")
